/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PosterIndexRouteImport } from './routes/poster/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PresentationsWasIstKiRouteImport } from './routes/presentations/was-ist-ki'
import { Route as PresentationsDatenschutzRouteImport } from './routes/presentations/datenschutz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterIndexRoute = PosterIndexRouteImport.update({
  id: '/poster/',
  path: '/poster/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsWasIstKiRoute = PresentationsWasIstKiRouteImport.update({
  id: '/presentations/was-ist-ki',
  path: '/presentations/was-ist-ki',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsDatenschutzRoute =
  PresentationsDatenschutzRouteImport.update({
    id: '/presentations/datenschutz',
    path: '/presentations/datenschutz',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presentations/datenschutz': typeof PresentationsDatenschutzRoute
  '/presentations/was-ist-ki': typeof PresentationsWasIstKiRoute
  '/docs': typeof DocsIndexRoute
  '/poster': typeof PosterIndexRoute
  '/presentations': typeof PresentationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presentations/datenschutz': typeof PresentationsDatenschutzRoute
  '/presentations/was-ist-ki': typeof PresentationsWasIstKiRoute
  '/docs': typeof DocsIndexRoute
  '/poster': typeof PosterIndexRoute
  '/presentations': typeof PresentationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presentations/datenschutz': typeof PresentationsDatenschutzRoute
  '/presentations/was-ist-ki': typeof PresentationsWasIstKiRoute
  '/docs/': typeof DocsIndexRoute
  '/poster/': typeof PosterIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/presentations/datenschutz'
    | '/presentations/was-ist-ki'
    | '/docs'
    | '/poster'
    | '/presentations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/presentations/datenschutz'
    | '/presentations/was-ist-ki'
    | '/docs'
    | '/poster'
    | '/presentations'
  id:
    | '__root__'
    | '/'
    | '/presentations/datenschutz'
    | '/presentations/was-ist-ki'
    | '/docs/'
    | '/poster/'
    | '/presentations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresentationsDatenschutzRoute: typeof PresentationsDatenschutzRoute
  PresentationsWasIstKiRoute: typeof PresentationsWasIstKiRoute
  DocsIndexRoute: typeof DocsIndexRoute
  PosterIndexRoute: typeof PosterIndexRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/': {
      id: '/poster/'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/was-ist-ki': {
      id: '/presentations/was-ist-ki'
      path: '/presentations/was-ist-ki'
      fullPath: '/presentations/was-ist-ki'
      preLoaderRoute: typeof PresentationsWasIstKiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/datenschutz': {
      id: '/presentations/datenschutz'
      path: '/presentations/datenschutz'
      fullPath: '/presentations/datenschutz'
      preLoaderRoute: typeof PresentationsDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresentationsDatenschutzRoute: PresentationsDatenschutzRoute,
  PresentationsWasIstKiRoute: PresentationsWasIstKiRoute,
  DocsIndexRoute: DocsIndexRoute,
  PosterIndexRoute: PosterIndexRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
