/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationsRouteImport } from './routes/presentations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosterIndexRouteImport } from './routes/poster/index'

const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterIndexRoute = PosterIndexRouteImport.update({
  id: '/poster/',
  path: '/poster/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRoute
  '/poster': typeof PosterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRoute
  '/poster': typeof PosterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRoute
  '/poster/': typeof PosterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/presentations' | '/poster'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/presentations' | '/poster'
  id: '__root__' | '/' | '/presentations' | '/poster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresentationsRoute: typeof PresentationsRoute
  PosterIndexRoute: typeof PosterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/': {
      id: '/poster/'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresentationsRoute: PresentationsRoute,
  PosterIndexRoute: PosterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
